name: Build My Dylib
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile Dylib
        run: |
          clang -dynamiclib -arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) \
          -framework Foundation -framework UIKit -framework CoreGraphics -framework QuartzCore \
          -fobjc-arc -o YallaLudoAutoClicker.dylib YLAutoClicker_Final_Code.m
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: MyDylib
          path: YallaLudoAutoClicker.dylib
